### ISSUE TITLE
Creating Hologram crashes all clients and server upon login

### ISSUE THREAD

**Issue by coderrquitsreality** [Creeperface01/Holograms#10]
23:36:50 [FATAL] Exception happened while ticking server
java.lang.IncompatibleClassChangeError: Found interface com.creeperface.nukkit.placeholderapi.api.PlaceholderAPI, but class was expected
        at gt.creeperface.holograms.placeholder.PlaceholderAPIAdapter.getLanguage(PlaceholderAPIAdapter.java:130) ~[?:?]
        at gt.creeperface.holograms.Holograms.getLanguage(Holograms.java:633) ~[?:?]
        at gt.creeperface.holograms.task.HologramUpdater.update(HologramUpdater.java:747) ~[?:?]
        at gt.creeperface.holograms.task.HologramUpdater.update(HologramUpdater.java:670) ~[?:?]
        at gt.creeperface.holograms.Hologram.spawnEntity(Hologram.java:113) ~[?:?]
        at gt.creeperface.holograms.entity.HologramEntity.spawnTo(HologramEntity.java:181) ~[?:?]
        at cn.nukkit.Player.doFirstSpawn(Player.java:887) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Player.sendNextChunk(Player.java:838) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Player.checkNetwork(Player.java:1798) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.tick(Server.java:1179) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.tickProcessor(Server.java:938) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.start(Server.java:906) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.<init>(Server.java:587) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:120) [nukkit-1.0-SNAPSHOT.jar:?]
23:36:50 [FATAL]
"main" prio=5 Id=1 RUNNABLE
        at java.management@11.0.9.1/sun.management.ThreadImpl.dumpThreads0(Native Method)
        at java.management@11.0.9.1/sun.management.ThreadImpl.dumpAllThreads(ThreadImpl.java:521)
        at java.management@11.0.9.1/sun.management.ThreadImpl.dumpAllThreads(ThreadImpl.java:509)
        at app//cn.nukkit.utils.Utils.getAllThreadDumps(Utils.java:112)
        at app//cn.nukkit.Server.tickProcessor(Server.java:970)
        at app//cn.nukkit.Server.start(Server.java:906)
        at app//cn.nukkit.Server.<init>(Server.java:587)
        at app//cn.nukkit.Nukkit.main(Nukkit.java:120)

"Reference Handler" daemon prio=10 Id=2 RUNNABLE
        at java.base@11.0.9.1/java.lang.ref.Reference.waitForReferencePendingList(Native Method)
        at java.base@11.0.9.1/java.lang.ref.Reference.processPendingReferences(Reference.java:241)
        at java.base@11.0.9.1/java.lang.ref.Reference$ReferenceHandler.run(Reference.java:213)

"Finalizer" daemon prio=8 Id=3 WAITING on java.lang.ref.ReferenceQueue$Lock@89590
        at java.base@11.0.9.1/java.lang.Object.wait(Native Method)
        -  waiting on java.lang.ref.ReferenceQueue$Lock@89590
        at java.base@11.0.9.1/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155)
        at java.base@11.0.9.1/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:176)
        at java.base@11.0.9.1/java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:170)

"Signal Dispatcher" daemon prio=9 Id=4 RUNNABLE

"Common-Cleaner" daemon prio=8 Id=9 TIMED_WAITING on java.lang.ref.ReferenceQueue$Lock@1b63133
        at java.base@11.0.9.1/java.lang.Object.wait(Native Method)
        -  waiting on java.lang.ref.ReferenceQueue$Lock@1b63133
        at java.base@11.0.9.1/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155)
        at java.base@11.0.9.1/jdk.internal.ref.CleanerImpl.run(CleanerImpl.java:148)
        at java.base@11.0.9.1/java.lang.Thread.run(Thread.java:834)
        at java.base@11.0.9.1/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:134)

"process reaper" daemon prio=10 Id=11 TIMED_WAITING on java.util.concurrent.SynchronousQueue$TransferStack@1eba2e
        at java.base@11.0.9.1/jdk.internal.misc.Unsafe.park(Native Method)
        -  waiting on java.util.concurrent.SynchronousQueue$TransferStack@1eba2e
        at java.base@11.0.9.1/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
        at java.base@11.0.9.1/java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:462)
        at java.base@11.0.9.1/java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:361)
        at java.base@11.0.9.1/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:937)
        at java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1053)
        at java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1114)
        at java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        ...

"Thread-0" prio=5 Id=15 RUNNABLE (in native)
        at java.base@11.0.9.1/java.io.FileInputStream.read0(Native Method)
        at java.base@11.0.9.1/java.io.FileInputStream.read(FileInputStream.java:231)
        at app//org.jline.terminal.impl.AbstractPty$PtyInputStream.read(AbstractPty.java:65)
        at app//org.jline.utils.NonBlockingInputStream.read(NonBlockingInputStream.java:62)
        at app//org.jline.utils.NonBlocking$NonBlockingInputStreamReader.read(NonBlocking.java:168)
        at app//org.jline.utils.NonBlockingReader.read(NonBlockingReader.java:57)
        at app//org.jline.keymap.BindingReader.readCharacter(BindingReader.java:133)
        at app//org.jline.keymap.BindingReader.readBinding(BindingReader.java:110)
        ...

"pool-3-thread-1" prio=5 Id=17 TIMED_WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@1c6f0fc
        at java.base@11.0.9.1/jdk.internal.misc.Unsafe.park(Native Method)
        -  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@1c6f0fc
        at java.base@11.0.9.1/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
        at java.base@11.0.9.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2123)
        at java.base@11.0.9.1/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1182)
        at java.base@11.0.9.1/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899)
        at java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1054)
        at java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1114)
        at java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        ...

"Network Listener - #0" daemon prio=5 Id=18 RUNNABLE
        at java.base@11.0.9.1/sun.nio.ch.EPoll.wait(Native Method)
        at java.base@11.0.9.1/sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:120)
        at java.base@11.0.9.1/sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:124)
        -  locked io.netty.channel.nio.SelectedSelectionKeySet@11455c1
        -  locked sun.nio.ch.EPollSelectorImpl@1dfd939
        at java.base@11.0.9.1/sun.nio.ch.SelectorImpl.select(SelectorImpl.java:136)
        at app//io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
        at app//io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:824)
        at app//io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:457)
        at app//io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
        ...

"Network Listener - #1" daemon prio=5 Id=19 RUNNABLE
        at java.base@11.0.9.1/sun.nio.ch.EPoll.wait(Native Method)
        at java.base@11.0.9.1/sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:120)
        at java.base@11.0.9.1/sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:124)
        -  locked io.netty.channel.nio.SelectedSelectionKeySet@c9d826
        -  locked sun.nio.ch.EPollSelectorImpl@1a9613
        at java.base@11.0.9.1/sun.nio.ch.SelectorImpl.select(SelectorImpl.java:136)
        at app//io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
        at app//io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:824)
        at app//io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:457)
        at app//io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
        ...

"Network Listener - #2" daemon prio=5 Id=20 RUNNABLE
        at java.base@11.0.9.1/sun.nio.ch.EPoll.wait(Native Method)
        at java.base@11.0.9.1/sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:120)
        at java.base@11.0.9.1/sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:124)
        -  locked io.netty.channel.nio.SelectedSelectionKeySet@1d17c0c
        -  locked sun.nio.ch.EPollSelectorImpl@1e789e
        at java.base@11.0.9.1/sun.nio.ch.SelectorImpl.select(SelectorImpl.java:136)
        at app//io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
        at app//io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:824)
        at app//io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:457)
        at app//io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
        ...

"Network Listener - #3" daemon prio=5 Id=21 RUNNABLE
        at java.base@11.0.9.1/sun.nio.ch.EPoll.wait(Native Method)
        at java.base@11.0.9.1/sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:120)
        at java.base@11.0.9.1/sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:124)
        -  locked io.netty.channel.nio.SelectedSelectionKeySet@a680d3
        -  locked sun.nio.ch.EPollSelectorImpl@b42a5a
        at java.base@11.0.9.1/sun.nio.ch.SelectorImpl.select(SelectorImpl.java:136)
        at app//io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
        at app//io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:824)
        at app//io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:457)
        at app//io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
        ...

"Network Listener - #4" daemon prio=5 Id=22 RUNNABLE
        at java.base@11.0.9.1/sun.nio.ch.EPoll.wait(Native Method)
        at java.base@11.0.9.1/sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:120)
        at java.base@11.0.9.1/sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:124)
        -  locked io.netty.channel.nio.SelectedSelectionKeySet@131edc
        -  locked sun.nio.ch.EPollSelectorImpl@1fe4788
        at java.base@11.0.9.1/sun.nio.ch.SelectorImpl.select(SelectorImpl.java:136)
        at app//io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
        at app//io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:824)
        at app//io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:457)
        at app//io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
        ...

"Network Listener - #5" daemon prio=5 Id=23 RUNNABLE
        at java.base@11.0.9.1/sun.nio.ch.EPoll.wait(Native Method)
        at java.base@11.0.9.1/sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:120)
        at java.base@11.0.9.1/sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:124)
        -  locked io.netty.channel.nio.SelectedSelectionKeySet@11ef2fc
        -  locked sun.nio.ch.EPollSelectorImpl@95ebff
        at java.base@11.0.9.1/sun.nio.ch.SelectorImpl.select(SelectorImpl.java:136)
        at app//io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
        at app//io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:824)
        at app//io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:457)
        at app//io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
        ...

"Network Listener - #6" daemon prio=5 Id=24 RUNNABLE
        at java.base@11.0.9.1/sun.nio.ch.EPoll.wait(Native Method)
        at java.base@11.0.9.1/sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:120)
        at java.base@11.0.9.1/sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:124)
        -  locked io.netty.channel.nio.SelectedSelectionKeySet@b2f8cf
        -  locked sun.nio.ch.EPollSelectorImpl@1ef2d16
        at java.base@11.0.9.1/sun.nio.ch.SelectorImpl.select(SelectorImpl.java:136)
        at app//io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
        at app//io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:824)
        at app//io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:457)
        at app//io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
        ...

"Network Listener - #7" daemon prio=5 Id=25 RUNNABLE
        at java.base@11.0.9.1/sun.nio.ch.EPoll.wait(Native Method)
        at java.base@11.0.9.1/sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:120)
        at java.base@11.0.9.1/sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:124)
        -  locked io.netty.channel.nio.SelectedSelectionKeySet@1bcb545
        -  locked sun.nio.ch.EPollSelectorImpl@99745e
        at java.base@11.0.9.1/sun.nio.ch.SelectorImpl.select(SelectorImpl.java:136)
        at app//io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
        at app//io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:824)
        at app//io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:457)
        at app//io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
        ...

"Java2D Disposer" daemon prio=10 Id=28 WAITING on java.lang.ref.ReferenceQueue$Lock@1f88502
        at java.base@11.0.9.1/java.lang.Object.wait(Native Method)
        -  waiting on java.lang.ref.ReferenceQueue$Lock@1f88502
        at java.base@11.0.9.1/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155)
        at java.base@11.0.9.1/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:176)
        at java.desktop@11.0.9.1/sun.java2d.Disposer.run(Disposer.java:144)
        at java.base@11.0.9.1/java.lang.Thread.run(Thread.java:834)

"Timer-0" prio=5 Id=29 WAITING on java.util.TaskQueue@11b9836
        at java.base@11.0.9.1/java.lang.Object.wait(Native Method)
        -  waiting on java.util.TaskQueue@11b9836
        at java.base@11.0.9.1/java.lang.Object.wait(Object.java:328)
        at java.base@11.0.9.1/java.util.TimerThread.mainLoop(Timer.java:527)
        at java.base@11.0.9.1/java.util.TimerThread.run(Timer.java:506)

"Timer-1" daemon prio=5 Id=30 TIMED_WAITING on java.util.TaskQueue@12f18cd
        at java.base@11.0.9.1/java.lang.Object.wait(Native Method)
        -  waiting on java.util.TaskQueue@12f18cd
        at java.base@11.0.9.1/java.util.TimerThread.mainLoop(Timer.java:553)
        at java.base@11.0.9.1/java.util.TimerThread.run(Timer.java:506)

"Watchdog" prio=5 Id=32 TIMED_WAITING on cn.nukkit.utils.Watchdog@f7a872
        at java.base@11.0.9.1/java.lang.Object.wait(Native Method)
        -  waiting on cn.nukkit.utils.Watchdog@f7a872
        at app//cn.nukkit.utils.Watchdog.run(Watchdog.java:64)

"Nukkit Asynchronous Task Handler #0" daemon prio=5 Id=33 RUNNABLE (in native)
        at java.base@11.0.9.1/java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.base@11.0.9.1/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
        -  locked java.net.SocksSocketImpl@1defefb
        at java.base@11.0.9.1/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
        at java.base@11.0.9.1/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
        at java.base@11.0.9.1/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
        at java.base@11.0.9.1/java.net.Socket.connect(Socket.java:609)
        at java.base@11.0.9.1/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:289)
        at java.base@11.0.9.1/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
        ...

        Number of locked synchronizers = 1
        - java.util.concurrent.ThreadPoolExecutor$Worker@1e8b711

"Nukkit Asynchronous Task Handler #1" daemon prio=5 Id=34 RUNNABLE (in native)
        at java.base@11.0.9.1/java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.base@11.0.9.1/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
        -  locked java.net.PlainSocketImpl@2e7f70
        at java.base@11.0.9.1/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
        at java.base@11.0.9.1/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
        at java.base@11.0.9.1/java.net.Socket.connect(Socket.java:609)
        at java.base@11.0.9.1/java.net.Socket.connect(Socket.java:558)
        at java.base@11.0.9.1/sun.net.NetworkClient.doConnect(NetworkClient.java:182)
        at java.base@11.0.9.1/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
        ...

        Number of locked synchronizers = 1
        - java.util.concurrent.ThreadPoolExecutor$Worker@4a3867

"Nukkit Asynchronous Task Handler #2" daemon prio=5 Id=35 RUNNABLE (in native)
        at java.base@11.0.9.1/java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.base@11.0.9.1/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
        -  locked java.net.PlainSocketImpl@1bc3756
        at java.base@11.0.9.1/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
        at java.base@11.0.9.1/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
        at java.base@11.0.9.1/java.net.Socket.connect(Socket.java:609)
        at java.base@11.0.9.1/java.net.Socket.connect(Socket.java:558)
        at java.base@11.0.9.1/sun.net.NetworkClient.doConnect(NetworkClient.java:182)
        at java.base@11.0.9.1/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
        ...

        Number of locked synchronizers = 1
        - java.util.concurrent.ThreadPoolExecutor$Worker@199df7a

"Timer-2" daemon prio=5 Id=36 TIMED_WAITING on java.util.TaskQueue@1c95292
        at java.base@11.0.9.1/java.lang.Object.wait(Native Method)
        -  waiting on java.util.TaskQueue@1c95292
        at java.base@11.0.9.1/java.util.TimerThread.mainLoop(Timer.java:553)
        at java.base@11.0.9.1/java.util.TimerThread.run(Timer.java:506)

"pool-7-thread-1" prio=5 Id=37 TIMED_WAITING on java.util.concurrent.SynchronousQueue$TransferStack@143c73a
        at java.base@11.0.9.1/jdk.internal.misc.Unsafe.park(Native Method)
        -  waiting on java.util.concurrent.SynchronousQueue$TransferStack@143c73a
        at java.base@11.0.9.1/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
        at java.base@11.0.9.1/java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:462)
        at java.base@11.0.9.1/java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:361)
        at java.base@11.0.9.1/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:937)
        at java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1053)
        at java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1114)
        at java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        ...

"Nukkit Asynchronous Task Handler #3" daemon prio=5 Id=38 RUNNABLE (in native)
        at java.base@11.0.9.1/java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.base@11.0.9.1/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
        -  locked java.net.SocksSocketImpl@1d483dc
        at java.base@11.0.9.1/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
        at java.base@11.0.9.1/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
        at java.base@11.0.9.1/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
        at java.base@11.0.9.1/java.net.Socket.connect(Socket.java:609)
        at java.base@11.0.9.1/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:289)
        at java.base@11.0.9.1/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
        ...

        Number of locked synchronizers = 1
        - java.util.concurrent.ThreadPoolExecutor$Worker@75af65

"Nukkit Asynchronous Task Handler #4" daemon prio=5 Id=39 BLOCKED on com.boydti.fawe.util.Updater@1aecd21 owned by "Nukkit Asynchronous Task Handler #3" Id=38
        at com.boydti.fawe.util.Updater.getUpdate(Updater.java:73)
        -  blocked on com.boydti.fawe.util.Updater@1aecd21
        at com.boydti.fawe.Fawe.update(Fawe.java:306)
        at com.boydti.fawe.Fawe.lambda$new$3(Fawe.java:294)
        at com.boydti.fawe.Fawe$$Lambda$354/0xa191d028.run(Unknown Source)
        at java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base@11.0.9.1/java.lang.Thread.run(Thread.java:834)

        Number of locked synchronizers = 1
        - java.util.concurrent.ThreadPoolExecutor$Worker@1a2c4dc

"pool-8-thread-1" prio=5 Id=41 TIMED_WAITING on java.util.concurrent.SynchronousQueue$TransferStack@1ba8929
        at java.base@11.0.9.1/jdk.internal.misc.Unsafe.park(Native Method)
        -  waiting on java.util.concurrent.SynchronousQueue$TransferStack@1ba8929
        at java.base@11.0.9.1/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
        at java.base@11.0.9.1/java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:462)
        at java.base@11.0.9.1/java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:361)
        at java.base@11.0.9.1/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:937)
        at java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1053)
        at java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1114)
        at java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        ...

"Thread-13" daemon prio=5 Id=42 TIMED_WAITING
        at java.base@11.0.9.1/java.lang.Thread.sleep(Native Method)
        at gt.creeperface.holograms.task.HologramUpdater.run(HologramUpdater.java:146)

"Timer-3" prio=5 Id=43 WAITING on java.util.TaskQueue@b5225b
        at java.base@11.0.9.1/java.lang.Object.wait(Native Method)
        -  waiting on java.util.TaskQueue@b5225b
        at java.base@11.0.9.1/java.lang.Object.wait(Object.java:328)
        at java.base@11.0.9.1/java.util.TimerThread.mainLoop(Timer.java:527)
        at java.base@11.0.9.1/java.util.TimerThread.run(Timer.java:506)

"Timer-4" daemon prio=5 Id=45 TIMED_WAITING on java.util.TaskQueue@1035d0c
        at java.base@11.0.9.1/java.lang.Object.wait(Native Method)
        -  waiting on java.util.TaskQueue@1035d0c
        at java.base@11.0.9.1/java.util.TimerThread.mainLoop(Timer.java:553)
        at java.base@11.0.9.1/java.util.TimerThread.run(Timer.java:506)

"pool-10-thread-1" prio=5 Id=46 TIMED_WAITING on java.util.concurrent.SynchronousQueue$TransferStack@4f4888
        at java.base@11.0.9.1/jdk.internal.misc.Unsafe.park(Native Method)
        -  waiting on java.util.concurrent.SynchronousQueue$TransferStack@4f4888
        at java.base@11.0.9.1/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
        at java.base@11.0.9.1/java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:462)
        at java.base@11.0.9.1/java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:361)
        at java.base@11.0.9.1/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:937)
        at java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1053)
        at java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1114)
        at java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        ...

"Nukkit Asynchronous Task Handler #5" daemon prio=5 Id=47 BLOCKED on com.boydti.fawe.util.Updater@4502d6 owned by "Nukkit Asynchronous Task Handler #0" Id=33
        at com.boydti.fawe.util.Updater.getUpdate(Updater.java:73)
        -  blocked on com.boydti.fawe.util.Updater@4502d6
        at com.boydti.fawe.Fawe.update(Fawe.java:306)
        at com.boydti.fawe.Fawe.lambda$new$3(Fawe.java:294)
        at com.boydti.fawe.Fawe$$Lambda$408/0x9ff65a28.run(Unknown Source)
        at java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base@11.0.9.1/java.lang.Thread.run(Thread.java:834)

        Number of locked synchronizers = 1
        - java.util.concurrent.ThreadPoolExecutor$Worker@136e4ba

"pool-8-thread-2" prio=5 Id=85 TIMED_WAITING on java.util.concurrent.SynchronousQueue$TransferStack@1ba8929
        at java.base@11.0.9.1/jdk.internal.misc.Unsafe.park(Native Method)
        -  waiting on java.util.concurrent.SynchronousQueue$TransferStack@1ba8929
        at java.base@11.0.9.1/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
        at java.base@11.0.9.1/java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:462)
        at java.base@11.0.9.1/java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:361)
        at java.base@11.0.9.1/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:937)
        at java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1053)
        at java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1114)
        at java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        ...

"pool-8-thread-3" prio=5 Id=86 TIMED_WAITING on java.util.concurrent.SynchronousQueue$TransferStack@1ba8929
        at java.base@11.0.9.1/jdk.internal.misc.Unsafe.park(Native Method)
        -  waiting on java.util.concurrent.SynchronousQueue$TransferStack@1ba8929
        at java.base@11.0.9.1/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
        at java.base@11.0.9.1/java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:462)
        at java.base@11.0.9.1/java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:361)
        at java.base@11.0.9.1/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:937)
        at java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1053)
        at java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1114)
        at java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        ...

**Comment by Creeperface01** [comment]
Update to latest holograms and placeholderapi
