### ISSUE TITLE
Some Error Prompt

### ISSUE THREAD

**Issue by ghost** [Creeperface01/Holograms#3]
[FATAL] Could not process hologram spawn request
cn.nukkit.utils.PluginException: Plugin 'Holograms' attempted to register a task while disabled.
at cn.nukkit.scheduler.ServerScheduler.addTask(ServerScheduler.java:239) ~[nukkit-1.0-SNAPSHOT.jar:?]
at cn.nukkit.scheduler.ServerScheduler.scheduleTask(ServerScheduler.java:52) ~[nukkit-1.0-SNAPSHOT.jar:?]
at gt.creeperface.holograms.task.HologramUpdater.sendPackets(HologramUpdater.java:628) ~[Holograms.jar:?]
at gt.creeperface.holograms.task.HologramUpdater.spawnHologramToAll(HologramUpdater.java:331) ~[Holograms.jar:?]
at gt.creeperface.holograms.task.HologramUpdater.spawnHologram(HologramUpdater.java:147) ~[Holograms.jar:?]
at gt.creeperface.holograms.task.HologramUpdater.run(HologramUpdater.java:78) [Holograms.jar:?]

How to fix it?

**Comment by Creeperface01** [comment]
Don't reload the server 😅

**Comment by ghost** [comment]
> Don't reload the server 😅

Oh,Thanks you😊
